# Generated by Django 4.1.2 on 2022-11-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.CharField(max_length=100),
        ),
    ]
