# Generated by Django 4.1.2 on 2022-10-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('time', models.TimeField()),
                ('sender', models.CharField(max_length=10)),
            ],
        ),
    ]
