# Generated by Django 4.1.2 on 2022-10-26 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Type', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('File', models.TextField()),
                ('FileType', models.CharField(max_length=20)),
                ('FolderName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.folder')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('upload', models.FileField(upload_to='files')),
                ('FileType', models.CharField(max_length=20)),
                ('FolderName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.folder')),
            ],
        ),
    ]
