# Generated by Django 4.1.2 on 2022-10-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='FolderName',
            field=models.CharField(max_length=100),
        ),
    ]
