# Generated by Django 4.1.2 on 2022-10-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_textfile_foldername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textfile',
            name='FileType',
        ),
    ]
