# Generated by Django 4.1.2 on 2022-11-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_textfile_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalfile',
            name='FolderName',
            field=models.CharField(max_length=1000),
        ),
    ]
