# Generated by Django 4.1.2 on 2022-11-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_externalfile_foldername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalfile',
            name='FileType',
            field=models.CharField(choices=[('Document', 'Document'), ('Image', 'Image'), ('Audio', 'Audio')], max_length=100),
        ),
    ]
