# Generated by Django 4.1.2 on 2022-11-24 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_externalfile_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalfile',
            name='FileType',
        ),
    ]
