# Generated by Django 4.1.2 on 2022-11-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_remove_externalfile_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalfile',
            name='Note',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
