# Generated by Django 4.1.2 on 2022-11-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_externalfile_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('upload', models.ImageField(upload_to='file')),
                ('FolderName', models.CharField(max_length=1000)),
                ('Note', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
