# Generated by Django 4.1.2 on 2022-11-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_audiofile_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.RemoveField(
            model_name='externalfile',
            name='Note',
        ),
        migrations.AddField(
            model_name='externalfile',
            name='FileType',
            field=models.CharField(choices=[('Document', 'Document'), ('Image', 'Image'), ('Audio', 'Audio')], default='Image', max_length=100),
            preserve_default=False,
        ),
    ]
