# Generated by Django 4.1.2 on 2022-11-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_delete_audiofile_remove_externalfile_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalfile',
            name='Notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='externalfile',
            name='upload',
            field=models.FileField(upload_to='file'),
        ),
    ]
